Formal_lang_task4
lanasheep/graph_DB pull request #4
Opened 2020-09-12 13:10 UTC by lanasheep

2020-09-15 06:14 UTC, gsvgit requested changes

2020-09-15 06:14 UTC, gsvgit commented on src/cyk.py
> +    dp = [[[] for i in range(100)] for i in range(100)]
а что это за магическая константа? Почему 100 хватит?

2020-09-15 06:14 UTC, gsvgit commented on src/cyk.py
> +        return "S000" in dict[eps]
См. предыдущую домашку. Жёсткая привязка к имени стартового --- не есть хорошо.

2020-09-15 06:14 UTC, gsvgit commented on src/cyk.py
> +                    if len(prod[1]) == 2 and (not is_term(prod[1][0])) and (not is_term(prod[1][1])) and \
Можно заранее профильтровать нужные продукции и здесь не тратить на это время на каждой итерации.

2020-09-25 08:12 UTC, gsvgit requested changes

2020-09-25 08:12 UTC, gsvgit commented on src/cyk.py
> +                        q.put((prod[0], u_, v))
А в какой момент Вы проверяете, что не обрабатываете один и тот же элемент два раза?

2020-09-25 08:12 UTC, gsvgit commented on src/cyk.py
> +                        q.put((prod[0], u_, v))
Есть ощущение, что это может приводить к зацикливанию. Старнно, что у Вас теста такого нет.

2020-09-27 09:23 UTC, lanasheep commented on src/cyk.py
> +                        q.put((prod[0], u_, v))
Вы имеете в виду добавление в очередь? Там проверка на нахождение в res, поэтому дважды не добавляется

2020-09-27 10:46 UTC, gsvgit commented
Да, извините, кажется, невнимательно код прочитал.

Regards,
Semyon Grigorev.


вс, 27 сент. 2020 г. в 12:23, lanasheep <notifications@github.com>:

> *@lanasheep* commented on this pull request.
> ------------------------------
>
> In src/cyk.py
> <https://github.com/lanasheep/graph_DB/pull/4#discussion_r495551138>:
>
> > +    filtered_prods = [prod for prod in prods if len(prod[1]) == 2 and \
>
> +                      (not is_term(prod[1][0])) and (not is_term(prod[1][1]))]
>
> +
>
> +    while not q.empty():
>
> +        nonterm, u, v = q.get()
>
> +        for nonterm_, u_, v_ in res:
>
> +            if v == u_:
>
> +                for prod in filtered_prods:
>
> +                    if  (prod[1][0] == nonterm) and (prod[1][1] == nonterm_) and ((prod[0], u, v_) not in res):
>
> +                        q.put((prod[0], u, v_))
>
> +                        res.append((prod[0], u, v_))
>
> +        for nonterm_, u_, v_ in res:
>
> +            if v_ == u:
>
> +                for prod in filtered_prods:
>
> +                    if (prod[1][0] == nonterm_) and (prod[1][1] == nonterm) and ((prod[0], u_, v) not in res):
>
> +                        q.put((prod[0], u_, v))
>
>
> Вы имеете в виду добавление в очередь? Там проверка на нахождение в res,
> поэтому дважды не добавляется
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/lanasheep/graph_DB/pull/4#discussion_r495551138>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQGKLJRAV7Z2GP3HBYDSH4AA5ANCNFSM4RJQBUYQ>
> .
>

2020-10-02 07:15 UTC, gsvgit approved these changes
Ок.

2021-09-26 14:19 UTC, merged