Formal_lang_task7
lanasheep/graph_DB pull request #7
Opened 2020-09-29 17:52 UTC by lanasheep

2020-10-02 07:26 UTC, gsvgit requested changes

2020-10-02 07:26 UTC, gsvgit commented on src/GraphQueries/GraphQueries.tokens
> +LBR=1
Мы на парах специально обсуждали, что выкладывать сгенерированные файлы --- зло. У Вас процесс сборки должен быть настроен так, чтобы спева генерировать то, что надо, потом запускать, тестировать и т.д.

2020-10-02 07:26 UTC, gsvgit commented on test/antlr_parser_tests.py
> +    tmp_file = tmp_path / "file.txt"
На конструкции типа connect, list не вижу тестов.

2020-10-02 08:44 UTC, lanasheep commented on src/GraphQueries/GraphQueries.tokens
> +LBR=1
Процесс сборки требовалось настроить в 8 задании, там он есть

2020-10-05 15:16 UTC, gsvgit approved these changes
Ок.

2021-09-26 14:19 UTC, merged